### ISSUE TITLE
Return error

### ISSUE THREAD

**Issue by Articmar** [ManeraKai/simplytranslate_mobile#220]
Android 6, MiUi 10.
When minimizing or returning to the previous application with the back button, I get the following error:

`java.lang.RuntimeException: Unable to destroy activity {com.simplytranslate_mobile/com.simplytranslate_mobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.googlecode.tesseract.android.TessBaseAPI.f()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4118)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4136)
	at android.app.ActivityThread.access$1700(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.googlecode.tesseract.android.TessBaseAPI.f()' on a null object reference
	at i1.a.c()
	at io.flutter.embedding.engine.c.x()
	at io.flutter.embedding.engine.c.y()
	at io.flutter.embedding.engine.c.z()
	at io.flutter.embedding.engine.c.m()
	at io.flutter.embedding.engine.a.e()
	at io.flutter.embedding.android.e.t()
	at io.flutter.embedding.android.d.onDestroy()
	at android.app.Activity.performDestroy(Activity.java:6510)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1149)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4105)
	... 9 more
`

**Comment by ManeraKai** [comment]
I have no idea why I didn't see this issue until now. I'll close is because things changed a lot.
